In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from scipy.optimize import curve_fit
from sklearn.metrics import mean_squared_error

# def fit_func(x, A, B, Epsilon_0, L_p, lam_p, x_A, x_B, a):
#     return Epsilon_0 + A * (math.e ** (-2 * x / L_p * np.sin(4 * math.pi * (x - x_A) / lam_p))) / (x ** (1/2)) + B * (math.e ** (-x / L_p * np.sin(2 * math.pi * (x - x_B) / lam_p))) / (x ** a)

data = pd.read_csv(r'/Users/brian_z/Desktop/Research/ET_hBN_fitting/S3_mat.csv')
initial = pd.read_csv(r'/Users/brian_z/Desktop/Research/ET_hBN_fitting/backup/recorded values.csv')
init = initial.values
values = data.values
print(values)
values = values[:,10:]
init = init[10:,:]
cut = np.load("slice.npy")
result = []
mse = []

# for i in range(len(cut[0])):
i = 0

A = init[i][1]
B = init[i][3]
Epsilon_0 = init[i][7]
L_p = init[i][5]
lam_p = init[i][6]
x_A = init[i][2]
x_B = init[i][4]
    
def fit_func(x, a):
    return Epsilon_0 + A * (math.e ** (-2 * x / L_p * np.sin(4 * math.pi * (x - x_A) / lam_p))) / (x ** (1/2)) + B * (math.e ** (-x / L_p * np.sin(2 * math.pi * (x - x_B) / lam_p))) / (x ** a)

ind_start = int(cut[1][i])
ind_end = int(cut[2][i])
x_list = np.linspace(1/60,5,300)
y_list = values[:,i]
x_list = x_list[ind_start:ind_end]
x_list = x_list - x_list[0] + 0.25
y_list = y_list[ind_start:ind_end]
y_list = y_list[::-1]
popt, pcov = curve_fit(fit_func, x_list, y_list, bounds=(0, 10), maxfev = 50000)
b = mean_squared_error(y_list, fit_func(x_list, *popt))
result.append(popt)
mse.append(b)
print(cut[0][i])
plt.plot(x_list, y_list)
plt.plot(x_list, fit_func(x_list, *popt), "*")
plt.show()



# x_list = np.linspace(1/60,5,300)
# frequencies = data.columns
# ind = np.where(frequencies == freq)[0][0]
# y_list = values[:,ind]
# x_list = x_list[ind_start:ind_end]
# x_list = x_list - x_list[0] + 0.25
# y_list = y_list[ind_start:ind_end]
# y_list = y_list[::-1]
# x_list = x_list[10:]
# y_list = y_list[10:]

# plt.plot(x_list, y_list)
# plt.plot(x_list[ind_start],y_list[ind_start],"r*")
# plt.plot(x_list[ind_end],y_list[ind_end],"r*")


[[1.11316915 1.17798958 1.23026993 ... 0.7598925  0.79485474 0.78231567]
 [1.11403305 1.1795655  1.23141825 ... 0.75996195 0.79225035 0.78214436]
 [1.11609005 1.18173379 1.23345223 ... 0.76031165 0.79115358 0.78413564]
 ...
 [1.01346383 1.00032648 0.98951082 ... 1.02127881 1.02145201 1.01861628]
 [1.01067406 0.99641525 0.9847141  ... 1.02056865 1.01857642 1.01497605]
 [1.00803321 0.99403429 0.97970151 ... 1.02061048 1.01923863 1.01437537]]


UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('float64'), dtype('<U6')) -> None

In [ ]:
# print(init)

In [ ]:
# def fit_func(x, A, B, Epsilon_0, L_p, lam_p, x_A, x_B, a):
#     return Epsilon_0 + A * (math.e ** (-2 * x / L_p * np.sin(4 * math.pi * (x - x_A) / lam_p))) / (x ** (1/2)) + B * (math.e ** (-x / L_p * np.sin(2 * math.pi * (x - x_B) / lam_p))) / (x ** a)
# def fit_func(x, A, B, Epsilon_0, L_p, lam_p, x_A, x_B, a):
#     return Epsilon_0 + A * (math.e ** (-2 * x / L_p * math.sin(4 * math.pi * (x - x_A) / lam_p))) / (x ** (1/2)) + B * (math.e ** (-x / L_p * math.sin(2 * math.pi * (x - x_B) / lam_p))) / (x ** a)
# def fit_func(x, a, b):
#     return a* (np.sin(x)) + b
# def fit_func(x, A, B, Epsilon_0, L_p, lam_p, x_A, x_B, a):
#     return Epsilon_0 + A * (math.e ** (-2 * x / L_p * np.sin(4 * math.pi * (x - x_A) / lam_p))) / (x ** (1/2)) + B * (math.e ** (-x / L_p * np.sin(2 * math.pi * (x - x_B) / lam_p))) / (x ** a) + 5.25542116e-10 + 2.87849263e-01 * (math.e ** (-2 * x / 1.76141737e+00 * np.sin(4 * math.pi * (x - 4.33354336e+00) / 5.77348970e+00))) / (x ** (1/2)) + 9.46007945e-01 * (math.e ** (-x / 1.76141737e+00 * np.sin(2 * math.pi * (x - 2.97882069e+00) / 5.77348970e+00))) / (x ** 2.59588092e-01)

In [ ]:
# popt, pcov = curve_fit(fit_func, x_list, y_list, bounds=([0,0,0,0,0,0,0,0], 5))
# popt, pcov = curve_fit(fit_func, x_list, y_list, bounds=([0,0,0,0,0,-np.inf,-np.inf,0],10), p0 = [0.1071,0.2526,1,3,1,9.9955,2.4025,1])

In [ ]:
# print(popt)

In [ ]:
# print(np.sqrt(np.diag(pcov)))

In [ ]:
# plt.plot(x_list, y_list)
# plt.plot(x_list, fit_func(x_list, *popt), "*")
# a = mean_squared_error(y_list, fit_func(x_list, *popt))
# print(a)

In [ ]:
# print(frequencies)